services:
  flask-blog-api:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: /bin/sh -c "python init_db.py && gunicorn --bind 0.0.0.0:5050 run:app"